version: "{build}"

build: off

clone_depth: 1

environment:
  matrix:
    - nodejs_version: 4
    - nodejs_version: 5

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - cmd: npm test
